name: MemoryCards-ECS CI/CD

on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'

#to run ci/cd manually
  workflow_dispatch:
    

env:
  AWS_REGION: ap-south-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: development/memory-cards         # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read


jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Check out code and pull
      uses: actions/checkout@v2


     
    - name: install dependencies and Build the application
      run: |
         npm install -g http-server
         npx http-server

    - name: wait for server to be upload
      run: sleep 5


    - name: Run tests
      run: |
         curl http://localhost:8080

    - name: Stop application
      run: kill -9 $(lsof -t -i :8080)


    - name: Build Docker image
      run: |
         docker build -t my-app:latest .


    - name: Deploy testing environment
      run: docker run --name app-con -p 80:80 my-app  
      
    - name: Check running containers and existed images
      run: |
         docker ps -a
         docker images
        
    - name: wait application to be upload
      run: |
         sleep 5
          
    - name: Run tests
      run: |
         curl http://localhost:80

    - name: Remove testing environment
      run: |
         docker stop app-con
         docker rm app-con

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
         aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.ECR_SECRET_KEY }}
         aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: tag, and push image to Amazon ECR
      id: build-image #need to check it
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: v${{ github.run_number }}
      run: | 
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker tag my-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        


  CD:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

